# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Julien Balestrieri
email: julien.balestrieri@gmail.com
short_description: Video Game Developer
description: > # this means to ignore newlines until "baseurl:"
 Game Developper 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://jbalestr42.github.io" # the base hostname & protocol for your site
permalink: /:title/
future: true # show the future post

# Social media profiles - feel free to add more here
#twitter_username: SBootstrap
itchio_username: octostudio 
github_username: jbalestr42 
youtube_link: watch?v=cg8lez3gFoU&list=PLec5Kut1QJUBjts3Sq_sViOYdC-w8e5q8 
steam_link: true 
#facebook_username: StartBootstrap
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
linkedin_url: https://www.linkedin.com/in/julienbalestrieri/

# Address information
address_street: 20 rue de Gandren
address_city: Haute-Kontz
address_state: France
address_zip: 57480

# Build settings
markdown: kramdown

theme: jekyll-theme-slate